In [32]:
import pandas as pd
import sqlite3
import numpy as np

In [33]:
orders=pd.read_csv(f'C:\\Users\\user\\Desktop\\Exam\\Data\\Row\\orders_noisy.csv')
customers=pd.read_csv(f'C:\\Users\\user\\Desktop\\Exam\\Data\\Row\\customers_noisy.csv')

In [34]:
customers

    CustomerID FirstName    LastName              Email    JoinDate
0         -1.0      Mark       Twain     MARK@EMAIL.COM  2023-01-01
1          NaN     Laura       White    laura@email.com  2023-01-02
2         10.0       NaN         NaN   noname@email.com  2023-01-03
3         11.0      John         NaN     john@email.com  2023-01-04
4         12.0      Anna       Smith                NaN  2023-01-05
..         ...       ...         ...                ...         ...
95       103.0   Name103  Surname103  user103@email.com  2023-11-11
96       104.0   Name104  Surname104  user104@email.com  2023-02-10
97       105.0   Name105  Surname105  user105@email.com  2023-07-06
98       106.0   Name106  Surname106  user106@email.com  2023-08-01
99       107.0   Name107  Surname107  user107@email.com  2023-12-24

[100 rows x 5 columns]

In [35]:
orders

     OrderID  CustomerID   OrderDate OrderAmount     Status
0       -1.0         1.0  2023-10-01         250    Pending
1        NaN         2.0  2023-10-02         300    Shipped
2      101.0         NaN  2023-10-03         150    Pending
3      102.0      9999.0  2023-10-04         400    Pending
4      103.0         3.0  2023-10-05        -500    Shipped
..       ...         ...         ...         ...        ...
295    394.0        32.0  2023-10-25      968.18  Cancelled
296    395.0       106.0  2023-10-22      980.95  Cancelled
297    396.0        60.0  2023-10-03      801.15    Pending
298    397.0        47.0  2023-10-18      167.41    Shipped
299    398.0       100.0  2023-10-24      688.72  Cancelled

[300 rows x 5 columns]

In [36]:
customers = customers[customers["CustomerID"].notna() & (customers["CustomerID"] != -1)]
customers=customers[customers["FirstName"].notna() & (customers["FirstName"] != "" ) &
                    customers["LastName"].notna() & (customers["LastName"] != "")]
customers["Email"] = customers["Email"].str.lower()
customers = customers[customers["Email"].notna() & (customers["Email"] != "")]

In [12]:
customers.to_csv(f'C:\\Users\\user\\Desktop\\Exam\\Data\\Processed\\customers_clean.csv', index=False)

In [38]:
orders = orders[orders["OrderID"].notna() & (orders["OrderID"] != -1) & 
                orders["CustomerID"].notna() & (orders["CustomerID"] != -1)]
orders["OrderAmount"]= pd.to_numeric(orders["OrderAmount"], errors='coerce')
orders.loc[orders["OrderAmount"] < 0, "OrderAmount"] = pd.NA
valid_status=["Pending","Shipped", "Cancelled"]
orders["Status"]=orders["Status"].where(orders["Status"].isin(valid_status), "Pending")
orders

     OrderID  CustomerID   OrderDate  OrderAmount     Status
3      102.0      9999.0  2023-10-04       400.00    Pending
4      103.0         3.0  2023-10-05          NaN    Shipped
5      104.0         4.0  2023-10-06          NaN  Cancelled
6      105.0         5.0  2023-10-07          NaN    Pending
7      106.0         6.0  2023-10-08       200.00    Pending
..       ...         ...         ...          ...        ...
295    394.0        32.0  2023-10-25       968.18  Cancelled
296    395.0       106.0  2023-10-22       980.95  Cancelled
297    396.0        60.0  2023-10-03       801.15    Pending
298    397.0        47.0  2023-10-18       167.41    Shipped
299    398.0       100.0  2023-10-24       688.72  Cancelled

[297 rows x 5 columns]