In [61]:
import pandas as pd
import numpy as np
import sqlite3

In [62]:
customers = pd.read_csv('C:\\Users\\user\\Desktop\\Exam\\Data\\Row\\customers_noisy.csv')
orders = pd.read_csv("C:\\Users\\user\\Desktop\\Exam\\Data\\Row\\orders_noisy.csv")
customers

    CustomerID FirstName    LastName              Email    JoinDate
0         -1.0      Mark       Twain     MARK@EMAIL.COM  2023-01-01
1          NaN     Laura       White    laura@email.com  2023-01-02
2         10.0       NaN         NaN   noname@email.com  2023-01-03
3         11.0      John         NaN     john@email.com  2023-01-04
4         12.0      Anna       Smith                NaN  2023-01-05
..         ...       ...         ...                ...         ...
95       103.0   Name103  Surname103  user103@email.com  2023-11-11
96       104.0   Name104  Surname104  user104@email.com  2023-02-10
97       105.0   Name105  Surname105  user105@email.com  2023-07-06
98       106.0   Name106  Surname106  user106@email.com  2023-08-01
99       107.0   Name107  Surname107  user107@email.com  2023-12-24

[100 rows x 5 columns]

In [63]:
customers =customers[
    customers["CustomerID"].notna() & (customers["CustomerID"] != -1)
    ]
customers = customers[
    customers["FirstName"].notna() & (customers["FirstName"] != "") 
    | customers["LastName"].notna() & (customers["LastName"] != "")]
customers["Email"] = customers["Email"].str.lower()
customers =customers[
    customers["Email"].notna() & (customers["Email"] != "")
    ]
customers

    CustomerID FirstName    LastName              Email    JoinDate
3         11.0      John         NaN     john@email.com  2023-01-04
5         13.0     Emily       Brown    emily@email.com  2023-01-06
6         14.0    Name14   Surname14   user14@email.com  2023-11-04
7         15.0    Name15   Surname15   user15@email.com  2023-01-24
8         16.0    Name16   Surname16   user16@email.com  2023-05-08
..         ...       ...         ...                ...         ...
95       103.0   Name103  Surname103  user103@email.com  2023-11-11
96       104.0   Name104  Surname104  user104@email.com  2023-02-10
97       105.0   Name105  Surname105  user105@email.com  2023-07-06
98       106.0   Name106  Surname106  user106@email.com  2023-08-01
99       107.0   Name107  Surname107  user107@email.com  2023-12-24

[96 rows x 5 columns]

In [64]:
customers.to_csv(f'C:\\Users\\user\\Desktop\\Exam\\Data\\Processed\\customers_clean1.csv', index=False)

In [65]:
orders

     OrderID  CustomerID   OrderDate OrderAmount     Status
0       -1.0         1.0  2023-10-01         250    Pending
1        NaN         2.0  2023-10-02         300    Shipped
2      101.0         NaN  2023-10-03         150    Pending
3      102.0      9999.0  2023-10-04         400    Pending
4      103.0         3.0  2023-10-05        -500    Shipped
..       ...         ...         ...         ...        ...
295    394.0        32.0  2023-10-25      968.18  Cancelled
296    395.0       106.0  2023-10-22      980.95  Cancelled
297    396.0        60.0  2023-10-03      801.15    Pending
298    397.0        47.0  2023-10-18      167.41    Shipped
299    398.0       100.0  2023-10-24      688.72  Cancelled

[300 rows x 5 columns]

In [66]:
orders = orders[
orders["CustomerID"].notna() & (orders["CustomerID"] != -1) &
orders["OrderID"].notna() & (orders["OrderID"] != -1)
    ]
orders["OrderAmount"] = pd.to_numeric(orders["OrderAmount"], errors='coerce')
orders.loc[orders["OrderAmount"] < 0, "OrderAmount"] = pd.NA
orders["OrderAmount"].fillna(orders["OrderAmount"].median(), inplace=True)

allowed_status = ["Pending", "Shipped", "Cancelled"]
orders["Status"] = orders["Status"].where(orders["Status"].isin(allowed_status), "Pending")
orders

C:\Users\user\AppData\Local\Temp\ipykernel_23472\3174909206.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  orders["OrderAmount"] = pd.to_numeric(orders["OrderAmount"], errors='coerce')
C:\Users\user\AppData\Local\Temp\ipykernel_23472\3174909206.py:7: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  orders["OrderAmount"].fillna(orders["OrderAmount"].median(), inplace=True)
C:\Users\user\AppData\Local\Temp\ipykernel_23472\3174909206.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  orders["OrderAmount"].fillna(orders["OrderAmount"].median(), inplace=True)
C:\Users\user\AppData\Local\Temp\ipykernel_23472\3174909206.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  orders["Status"] = orders["Status"].where(orders["Status"].isin(allowed_status), "Pending")

     OrderID  CustomerID   OrderDate  OrderAmount     Status
3      102.0      9999.0  2023-10-04       400.00    Pending
4      103.0         3.0  2023-10-05       555.34    Shipped
5      104.0         4.0  2023-10-06       555.34  Cancelled
6      105.0         5.0  2023-10-07       555.34    Pending
7      106.0         6.0  2023-10-08       200.00    Pending
..       ...         ...         ...          ...        ...
295    394.0        32.0  2023-10-25       968.18  Cancelled
296    395.0       106.0  2023-10-22       980.95  Cancelled
297    396.0        60.0  2023-10-03       801.15    Pending
298    397.0        47.0  2023-10-18       167.41    Shipped
299    398.0       100.0  2023-10-24       688.72  Cancelled

[297 rows x 5 columns]

In [59]:
customers.to_csv(f'C:\\Users\\user\\Desktop\\Exam\\Data\\Processed\\orders_clean1.csv', index=False)

In [67]:
clean_customers=pd.read_csv('C:\\Users\\user\\Desktop\\Exam\\Data\\Processed\\customers_clean1.csv')
clean_customers

    CustomerID FirstName    LastName              Email    JoinDate
0         11.0      John         NaN     john@email.com  2023-01-04
1         13.0     Emily       Brown    emily@email.com  2023-01-06
2         14.0    Name14   Surname14   user14@email.com  2023-11-04
3         15.0    Name15   Surname15   user15@email.com  2023-01-24
4         16.0    Name16   Surname16   user16@email.com  2023-05-08
..         ...       ...         ...                ...         ...
91       103.0   Name103  Surname103  user103@email.com  2023-11-11
92       104.0   Name104  Surname104  user104@email.com  2023-02-10
93       105.0   Name105  Surname105  user105@email.com  2023-07-06
94       106.0   Name106  Surname106  user106@email.com  2023-08-01
95       107.0   Name107  Surname107  user107@email.com  2023-12-24

[96 rows x 5 columns]

In [ ]:
valid_customers = set(clean_customers["CustomerID"])
orders_validate = orders[orders["CustomerID"].isin(valid_customers)]

In [77]:
orders_validate.to_csv("C:\\Users\\user\\Desktop\\Exam\\Data\\Processed\\orders_validated1.csv")

In [86]:
conn=sqlite3.connect("C:\\Users\\user\\Desktop\\Exam\\Data\\DB\\CustomerOrders.db")
cursor=conn.cursor()

In [87]:
clean_customers.to_sql("Customers", conn, if_exists="replace", index=False)
orders_validate.to_sql("Orders", conn, if_exists="replace", index=False)

291

In [98]:
cursor.executescript("""
DROP TABLE IF EXISTS Customers;
DROP TABLE IF EXISTS Orders;
DROP TABLE IF EXISTS OrderStatusLog;
""")

cursor.executescript( """
    CREATE TABLE Customers (
        CustomerID INTEGER PRIMARY KEY,
        FirstName TEXT,
        LastName TEXT,
        Email TEXT UNIQUE,
        JoinDate TEXT
    );
                     
    CREATE TABLE Orders (
        OrderID INTEGER PRIMARY KEY,
        CustomerID INTEGER,
        OrderDate TEXT,
        OrderAmount REAL,
        Status TEXT,
        FOREIGN KEY (CustomerID) REFERENCES Customers(CustomerID)
    );
                     
    CREATE TABLE OrderStatusLog (
        LogID INTEGER PRIMARY KEY AUTOINCREMENT,
        OrderID INTEGER,
        PreviousStatus TEXT,
        NewStatus TEXT,
        ChangeDate TEXT DEFAULT CURRENT_TIMESTAMP
    );
    """)

In [99]:
cursor.executescript("""
CREATE TRIGGER LogOrderStatusChange
AFTER UPDATE OF Status ON Orders
FOR EACH ROW
WHEN OLD.Status != NEW.Status
BEGIN               
    INSERT INTO OrderStatusLog (
        OrderID, 
        OldStatus, 
        NewStatus, 
        ChangeDate
    )
    VALUES (
        OLD.OrderID,
        OLD.Status,
        NEW.Status,
        CURRENT_TIMESTAMP
    );
END;
""")

In [107]:
cursor.executescript("""
DROP VIEW IF EXISTS CustomerRevenueSummary;
                     
CREATE VIEW CustomerRevenueSummary AS 
SELECT
    C.CustomerID,
    C.FirstName || " " || C.LastName AS FULL_NAME,
    COUNT(o.OrderID) AS TotalOrders,
    SUM(
        CASE
        WHEN o.Status= "Shipped"
        Then o.OrderAmount
        END
    ) AS TotalRevenue    
FROM Customers c
LEFT JOIN Orders o
    ON c.CustomerID == o.CustomerId
GROUP BY c.CustomerID               
                      """)

In [108]:
conn.commit()
conn.close()